# About the Author & Acknowledgements

## About Me

Hi, my name is Jamie and I’m an MRC-funded PhD student at UCL, focusing on the application of causal inference methods within Epidemiology, Data Science, and Health Economics.

Before my PhD, I previously graduated with a BSc in Population Health Sciences (Data Science) from UCL, and an NIHR funded MSc in Epidemiology from the London School of Hygiene and Tropical Medicine.

Prior to my PhD, my interest in researching the application of causal inference methods in observational data stemmed from my varied experience working across multiple areas of public health research, including supporting the delivery of cancer trials, evaluating obesity policy decisions, identifying barriers to STI testing, and investigating the long-term effects of cancer survivorship.

Having worked with both randomized trials and observational data, focusing my research on causal inference in real-world data felt like a natural next step.

If you have any questions do feel free to reach out to me via the following channels: 
UCL Email: jamie.wong [at] ucl.ac.uk
NHS Email: laichunjamie.wong [at] nhs.net
LinkedIn: https://www.linkedin.com/in/jamiewlc/
GitHub: https://github.com/jamiewlc

\

## Acknowledgements

This handbook was developed during my PhD placement with NHS England and the North Central London Integrated Care Board (NCL ICB) as part of the NHS England Data Science PhD Internship Programme. I am grateful to both organisations for providing the opportunity, data access, and collaborative environment that enabled this work.

I would like to express my sincere thanks to my internship supervisors, Jonathan Pearson (NHS England) and Emily Baldwin (NCL ICB), whose guidance, support, and encouragement were invaluable throughout the project.

I am also deeply grateful to my academic supervisors at UCL, Dr Michalis Katsoulis, Prof Manuel Gomes, and Dr Sophie Eastwood, for their continued support in shaping the causal analyses and the writing of this handbook.

I would also like to thank colleagues across the NHS England Applied Data Science and AI team and the NCL ICB Analytics team for their advice and feedback during the development of this work, especially Jo Lam and Adam Hollings at NHS England, as well as Tom Shallcross, Felix Peckitt, Anita Garrick, and Enrico Panizzo at the NCL ICB.